---
name: checkton
author: Adam Cmiel <acmiel@redhat.com>
description: Runs ShellCheck on Tekton yaml files (and other yaml files, but mainly Tekton)

branding:
  icon: check-circle
  color: purple

inputs:
  # inspired by https://github.com/redhat-plumbers-in-action/differential-shellcheck/blob/main/action.yml
  pull-request-base:
    description: Hash of top commit on base branch
    required: false
    default: ${{ github.event.pull_request.base.sha }}
  pull-request-head:
    description: Hash of latest commit in Pull Request
    required: false
    default: ${{ github.event.pull_request.head.sha }}

runs:
  using: docker
  image: Dockerfile
  env:
    BASE: ${{ inputs.pull-request-base }}
    HEAD: ${{ inputs.pull-request-head }}
