---
name: checkton
author: Adam Cmiel <acmiel@redhat.com>
description: Runs ShellCheck on Tekton yaml files (and other yaml files, but mainly Tekton)

branding:
  icon: check-circle
  color: purple

inputs:
  # inspired by https://github.com/redhat-plumbers-in-action/differential-shellcheck/blob/main/action.yml
  pull-request-base:
    description: Hash of the latest commit in the base branch.
    required: false
    default: ${{ github.event.pull_request.base.sha }}
  pull-request-head:
    description: Hash of the latest commit in the Pull Request.
    required: false
    default: ${{ github.event.pull_request.head.sha }}
  fail-on-findings:
    description: >-
      Fail when ShellCheck reports some findings? (May wish to set this to false if you're
      going to upload the SARIF report anyway. GitHub takes care of the reporting.)
    required: false
    default: true

outputs:
  sarif:
    description: Path to the generated SARIF report.

runs:
  using: docker
  image: Dockerfile
  env:
    CHECKTON_DIFF_BASE: ${{ inputs.pull-request-base }}
    CHECKTON_DIFF_HEAD: ${{ inputs.pull-request-head }}
    CHECKTON_FAIL_ON_FINDINGS: ${{ inputs.fail-on-findings }}
