FROM registry.fedoraproject.org/fedora-minimal:40@sha256:f1b88c87dcc0b6c4cc332e5a3a5a51e2719328d47c81cdf7d1c3b34078436265

RUN microdnf -y install \
        --setopt install_weak_deps=false \
        --setopt tsflags=nodocs \
        ${AUTOGENERATED_START:-} \
        csdiff-3.3.0-1.fc40 \
        git-2.45.1-1.fc40 \
        jq-1.7.1-7.fc40 \
        python-unversioned-command-3.12.3-2.fc40 \
        sarif-fmt-0.4.2-3.fc40 \
        ShellCheck-0.9.0-6.fc40 \
        ${AUTOGENERATED_END:-} \
    && microdnf clean all

COPY src/ /opt/checkton/

CMD ["/opt/checkton/action.sh"]
