FROM registry.fedoraproject.org/fedora-minimal:40@sha256:2d724b802b53e008ba99fa8460cbd47a54d6d129b8bfc0fad8034f97b70f416d

RUN microdnf -y install \
        --setopt install_weak_deps=false \
        --setopt tsflags=nodocs \
        ${AUTOGENERATED_START:-} \
        csdiff-3.3.0-1.fc40 \
        git-2.45.1-1.fc40 \
        jq-1.7.1-7.fc40 \
        python-unversioned-command-3.12.3-2.fc40 \
        sarif-fmt-0.4.2-3.fc40 \
        ShellCheck-0.9.0-6.fc40 \
        ${AUTOGENERATED_END:-} \
    && microdnf clean all

COPY src/ /opt/checkton/

CMD ["/opt/checkton/action.sh"]
