#!/bin/bash
set -o errexit -o nounset -o pipefail

base_image=$(awk '/FROM/ { print $2 }' Dockerfile)

mapfile -t updated_rpms < <(
    podman run --rm "$base_image" microdnf list \
        ShellCheck \
        csdiff \
        git \
        python-unversioned-command |
    awk '
        /Available packages/ { flag = 1; next }
        flag { sub(/\..*/, "", $1); printf "%s-%s\n", $1, $2 }
    ' | sort -u
    # ^ "ShellCheck.x86_64 0.9.0-6.fc40 fedora" -> "ShellCheck-0.9.0-6.fc40"
)

updated_dockerfile=$(
    awk '{ print } /AUTOGENERATED_START/ { exit }' Dockerfile
    printf '        %s \\\n' "${updated_rpms[@]}"
    awk '/AUTOGENERATED_END/,0' Dockerfile
)

printf "%s\n" "$updated_dockerfile" > Dockerfile
