name: Release
on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Verify that tag matches image version in action.yaml
        run: |
          #!/bin/bash
          set -e

          tag=${GITHUB_REF#refs/tags/}

          image=$(yq '.runs.image' action.yaml)
          image_without_digest=${image%@*}
          version=${image_without_digest##*:}

          if [[ "$tag" != "$version" ]]; then
              echo "Tag does not match action.yaml image version: $tag X $image" >&2
              exit 1
          fi

      - name: Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3
